version: '2'
services:
    jasper_gateway-app:
        image: jasper_gateway
        external_links:
            - jasper_gateway-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - jasper_gateway-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jasper_gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    jasper_gateway-postgresql:
        extends:
            file: postgresql.yml
            service: jasper_gateway-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: jasper_gateway-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
